version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: fastapi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-fastapi_db}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-rootpassword}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fastapi_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_server
    restart: always
    environment:
      - DEBUG=${DEBUG:-True}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-rootpassword}
      - DB_NAME=${DB_NAME:-fastapi_db}
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fastapi_network
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mysql_data:
    driver: local

networks:
  fastapi_network:
    driver: bridge
